version: 2

# Visit https://goreleaser.com for documentation on how to customize this behavior
builds:
  - binary: speedtest-exporter
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64

dockers:
  - id: linux_amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "{{.Env.IMAGENAME}}:{{.Tag}}"
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Now.Format "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.authors="Adrian Astley"
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.documentation={{.GitURL}}/README.md
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - -o=type=docker
    use: docker

gitlab_urls:
  api: https://gitlab.ct.activision.com/api/v4/
  download: https://gitlab.ct.activision.com
