name: release

on:
  push:
    branches:
      - main

env:
  IMAGENAME: ghcr.io/richiesams/speedtest-exporter
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup SVU
        id: svu
        uses: obfu5c8/action-svu@v1.0.0
        with:
          svu-version: 1.12.0
      - name: Create git tag
        run: git tag ${{ steps.svu.outputs.version }}
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v3.0.2
        with:
          args: --latest --strip all
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x
      - name: Build and push image
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v2.3.2
          args: release --clean --release-notes ${{ steps.git-cliff.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
