name: release

on:
  push:
    branches:
      - main

env:
  IMAGENAME: ghcr.io/richiesams/speedtest-exporter
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Re-fetch all tags
        run: git fetch --force --tags
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.x
      - name: Build and push image
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v2.3.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
